Check for permission to change speed
CFC-Servers/cfc_pvp_movespeed pull request #26
Opened 2021-03-31 17:36 UTC by legokidlogan

There may be times (such as with CFC Powerups) where we don't want to override move speed, so this adds a hook call for whether or not to stop the speed change.

2021-03-31 18:01 UTC, brandonsturgeon commented
So this works when the player equips or removes weapons while they have a powerup, but what about when they were _already_ slowed before the powerup?

2021-03-31 18:15 UTC, plally commented on lua/autorun/server/sv_pvp_movespeed.lua
> +    if hook.Run( generateCFCHook( "DisallowChangeMoveSpeed" ), ply ) ~= nil then return end
```suggestion
    if hook.Run( generateCFCHook( "CanChangeMovespeed" ), ply ) ~= false then return end
```

2021-04-15 20:04 UTC, overlordbleck reviewed
The code looks good but I think it's down to preference from @brandonsturgeon

2021-04-15 21:20 UTC, plally requested changes

2021-04-15 21:20 UTC, plally commented on lua/autorun/server/sv_pvp_movespeed.lua
> +hook.Add( "CFC_Powerups_PowerupRemoved", "CFC_PlyMS_PowerupRemoved", function( ply, powerupId )
why are we using our own custom hook here? why not a function?

2021-04-15 21:20 UTC, plally commented on lua/autorun/server/sv_pvp_movespeed.lua
> +hook.Add( "CFC_PlyMS_CanChangeMoveSpeed", "CFC_PlyMS_AccountForSpeedPowerup", function( ply )
the  whole point of using a hook for this check is so we can define the checks in another addon.

2021-04-15 21:23 UTC, plally commented on lua/autorun/server/sv_pvp_movespeed.lua
> +end )
im not sure this logic should be in this addon.

2021-05-22 01:53 UTC, brandonsturgeon approved these changes

2021-11-25 09:44 UTC, brandonsturgeon commented
Did we come to a conclusion on where the code for those hooks should lie? I remember no one really agreeing, and I see PCL's comments resolved. Is there a discord conversation to refer to?

2021-11-25 17:55 UTC, plally commented
there havent been any commits since my commets though...

2021-11-25 20:42 UTC, brandonsturgeon commented
Right, I'm trying to figure out why that happened. Was there a discussion about this somewhere else?

2021-11-25 21:20 UTC, legokidlogan commented
iirc there was, either in one of the dev channels or in vc

2022-12-14 20:53 UTC, legokidlogan commented
Closing in favor of #33, which does this (and some other compat fixes) much more cleanly, without needing to rely on changes in other addons.

2022-12-14 20:53 UTC, closed without merging